metaflowltd/flutter_health_fit

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
https://metaflow.atlassian.net/browse/LUM-4806
https://metaflow.atlassian.net/browse/LUM-4772
> Use getAccountForExtension instead of getLastSignedInAccount for cases when the user was signed out.

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- ios/flutter_health_fit.podspec
- lib/flutter_health_fit.dart
> heart-rate

- android/build.gradle
- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/android/build.gradle
- example/android/gradle.properties
Request for android.permission.BODY_SENSORS before connecting to Google Fit.
> heart-rate-permission

- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/flutter_health_fit.dart
Description
HealthFitPlugin Collect WaistSize and BodyFat
Checklist
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes ([x]). This will ensure a smooth and quick review process.
🎉   I added unit tests to all relevant code.
🏎   I updated related UI Automation Tests (on my own or with Yaniv's help).
🧮   I added analytics events (didn't get a spec? check with product).
✅   All existing and new unit tests are passing.
🏳   Feature flag added (if needed).
🤖   I verified functionality/proper UI visibility on Android platform.
🍏   I verified functionality/proper UI visibility iOS platform.
📜   I updated/added relevant documentation (doc comments with ///).
🩺   The analyzer (flutter analyze) does not report any problems on my PR.
💁🏼‍♀️ …
> LMN-643 | HealthFitPlugin Collect WaistSize and BodyFat

- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/flutter_health_fit.dart
Menstrual Cycle data from Apple Health
for this issue https://metaflow.atlassian.net/browse/LMN-3319
> LMN-3319 | Menstrual Cycle data from Apple Health

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/lib/main.dart
- lib/flutter_health_fit.dart
Please note, the feature is commented out with TODO note 
`// TODO remove after approval of reproductive_health scope`
> LMN-3963 | Menstrual cycle addition from GoogleFit

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/lib/main.dart
- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/flutter_health_fit.dart
related to these tickets 
LMN-3319: https://metaflow.atlassian.net/browse/LMN-3319
LMN-3963: https://metaflow.atlassian.net/browse/LMN-3963
> LMN-3319 | Collect Menstrual Cycle data

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/lib/main.dart
- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/flutter_health_fit.dart
LMN-3323 | HRV from Apple Health
LMN-4185 | realtime heart rate should be average and not latest
https://metaflow.atlassian.net/browse/LMN-4185
https://metaflow.atlassian.net/browse/LMN-3323
> LMN-3323 | HRV from Apple Health

- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/flutter_health_fit.dart
Bring Lab Results from Apple health
https://metaflow.atlassian.net/browse/LMN-4075
> LMN-4075 | Bring Lab Results from Apple health

- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/data_pointd_output.dart
- lib/flutter_health_fit.dart
Lab results collect sourceProvider on Apple health
https://metaflow.atlassian.net/browse/LMN-4206
> LMN-4206 | Lab results collect sourceProvider on Apple health

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/main.dart
- ios/Classes/DataPointValue.swift
- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/body_composition_data.dart
- lib/data_point_unit.dart
- lib/flutter_health_fit.dart
Collect sourceporvider for weight
https://metaflow.atlassian.net/browse/LMN-4361
> LMN-4361 | Collect sourceporvider for weight

- android/src/main/kotlin/com/metaflow/flutterhealthfit/DataPointValue.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/WorkoutsReader.kt
- ios/Classes/DataPointValue.swift
- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/data_point_unit.dart
- lib/flutter_health_fit.dart
Collect Energy Consumed from Google Fit
https://metaflow.atlassian.net/browse/LMN-4407
> LMN-4407 | Collect Energy Consumed from Google Fit

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/UserEnergyReader.kt
- lib/flutter_health_fit.dart
Collect BMR data point from GoogleFit
https://metaflow.atlassian.net/browse/LMN-4408
> LMN-4408 | Collect BMR data point from GoogleFit

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/UserEnergyReader.kt
- android/src/main/kotlin/com/metaflow/flutterhealthfit/WorkoutsReader.kt
- example/lib/main.dart
Workouts missing data
https://metaflow.atlassian.net/browse/LMN-4534
> LMN-4534 | Workouts missing data

- example/lib/main.dart
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- lib/flutter_health_fit.dart
SwiftFlutterHealthFitPlugin.swift line 684
https://metaflow.atlassian.net/browse/LMN-4804
> LMN-4804 | SwiftFlutterHealthFitPlugin.swift line 684

- lib/flutter_health_fit.dart
- changed authorize return type. The new HealthFitAuthorizationResult contains authorization status enum and an optional error object.
- moved platform exception check for userCancelled status from the app to the package for better responsibility separation.
> LMN-5201 | [Health fit] Provide authorization result with status

- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- ios/Classes/WorkoutsObserver.swift
- lib/flutter_health_fit.dart
- created workouts observer to receive update triggers from health kit.
> LMN-5543 | Subscribe to HealthKit changes

- example/ios/Runner.xcodeproj/project.pbxproj
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- ios/Classes/WorkoutsObserver.swift
- canceling workouts observation on flutter engine detach
> LMN-5836 | WorkoutsObserver - [Crashlytics] Crash in WorkoutsObserver after flutter engine detach

- ios/Classes/HealthkitReader.swift
- ios/Classes/SwiftFlutterHealthFitPlugin.swift
- fixed raw sleep data serialization within the "metadata".
- separated general sleep and raw sleep data queries.
> LMN-7462 | Raw sleep data serialization issue

- android/src/main/kotlin/com/metaflow/flutterhealthfit/WorkoutsReader.kt
- fixed workout session reporting crash when session's active time is not available
- added ongoing workout session check to skip ongoing sessions reporting.
>  Workout session reporting fix

- android/src/main/kotlin/com/metaflow/flutterhealthfit/WorkoutsReader.kt
- filtering out sleep fitness activity in the workouts read result.
> LMN-14937 | sleep sent from sync (Google fit) is registered as sleep and workout

- android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
- example/lib/main.dart
- Added required  "is activity recognition authorized" check to steps authorization.
> LMN-18136 | Android -  Error when calling steps
